mail_relay: smtp.nbi.ku.dk
mail_forward_root: neicweb-admins@ndgf.org

# ----BEGIN---- soon obsolete

jekyll_version: 2.5.3
django_version: 1.8.4

pip_virtualenv: /opt/python
pip_site_packages: "{{pip_virtualenv}}/lib/python2.7/site-packages"

# Access for triggering update.
neicweb_jekyll_update_allow:
  - 192.30.252.0/22
  - 130.236.101.0/25

# Directories
neicweb_top_dir: /var/www/neic.nordforsk.org
neicweb_cgi_dir: "{{neicweb_top_dir}}/cgi-bin"

# A list of the main site (used for DocumentRoot) followed by subsites.
neicweb_sites:
  neicweb:
    vhost: neic.nordforsk.org
    vpath: /
    webroot: "{{neicweb_top_dir}}/neicweb" # Parent of neicweb_document_root
    cgi_key: neicnordic-neicweb
    git_fetch_url: https://github.com/neicnordic/neicweb.git
  neicweb-devel:
    vhost: devel.neic.nordforsk.org
    webroot: "{{neicweb_top_dir}}/neicweb-devel"
    cgi_key: neicnordic-neicweb-devel
    git_fetch_url: https://github.com/neicnordic/neicweb-devel.git
  ahm16:
    vhost: ahm16.neic.nordforsk.org
    webroot: "{{neicweb_top_dir}}/ahm16"
    cgi_key: neicnordic-ahm16
    git_fetch_url: https://github.com/neicnordic/ahm16.git
jekyllweb_updater_trusted_repo: https://github.com/neicnordic/neicweb-extensions.git

# ----END---- soon obsolete
