### Automatic Updates

- name: Install cron job to run pip updates
  cron:
    name=pip_update cron_file=neicweb-ansible minute=37 hour=3 user=root
    job="{{pip_virtualenv}}/bin/pip freeze --local | grep -v '^\-e' | cut -d = -f 1  |
         xargs -n1 {{pip_command}} install -q --log {{pip_update_log}} -U"

- name: Install logrotate script for pip update log
  template:
    dest=/etc/logrotate.d/pip-update src=pip-update.logrotate.j2
    owner=root group=root mode=644
