### Software

- yum: name={{item}}
  with_items:
    - python-pillow
    - python-pip
    - python-virtualenv
    - python-requests
- pip: name=django virtualenv={{pip_virtualenv}} version={{django_version}}
- git: dest={{github_uploader_source_dir}}
       repo=https://github.com/neicnordic/github_uploader.git
       version=master

### Configuration

- file: dest={{github_uploader_config_dir}}
        state=directory owner=root group=apache mode=750
- template: dest={{github_uploader_config_dir}}/local_settings.py
            src=local_settings.py.j2
            owner=root group=apache mode=640

### Database

- file: dest={{github_uploader_data_dir}}
        state=directory owner=apache group=apache mode=750

- command: env PYTHONPATH={{pip_site_packages}}:{{github_uploader_config_dir}}
               python manage.py migrate
  args:
    chdir: "{{github_uploader_source_dir}}"
    creates: "{{github_uploader_data_dir}}/db.sqlite3"

- file: dest={{github_uploader_data_dir}}/db.sqlite3
        owner=apache group=apache mode=750

### Static Directories and Templates

- file: dest={{item.media_root}}
        state=directory owner=apache group=apache mode=755
  with_items: github_uploader_instances.values()

- file: dest={{item}}
        state=directory owner=root group=root mode=755
  with_items: github_uploader_template_dirs + github_uploader_staticfiles_dirs

- command: env PYTHONPATH={{pip_site_packages}}:{{github_uploader_config_dir}}
               python manage.py collectstatic --noinput
  args:
    chdir: "{{github_uploader_source_dir}}"

### Cron Job to Delete Stale Sessions

- file: dest=/var/log/github_uploader state=directory
        owner=apache group=apache mode=750
- cron: name=github_uploader_cleanup cron_file=neicweb-ansible minute=03 user=apache
        job="PYTHONPATH={{pip_site_packages}}:{{github_uploader_config_dir}} python {{github_uploader_source_dir}}/manage.py clearsessions_github > /var/log/github_uploader/clearsessions_github.log 2>&1"
