### System Software

- name: Install OS packages for Jekyll
  yum: name={{item}} state=present
  with_items:
    - epel-release
    - gcc
    - git
    - httpd             # for the apache user
    - pandoc
    - ruby
    - ruby-devel
    - rubygem-json
    - rubygem-ffi
    - rubygem-safe_yaml

- name: Install Ruby gems for Jekyll
  gem: user_install=no name={{item}} state=present
  with_items:
    - redcarpet
    - RedCloth
    - pandoc-ruby

- name: Install Jekyll
  gem: user_install=no name=jekyll state=present version={{jekyll_version}}

### Our Software

- name: Install jekyllweb_updater.py
  copy:
    dest={{jekyllweb_updater_program}}
    src=external/jekyllweb_updater/jekyllweb_updater.py
    owner=root group=root mode=755

- name: Install jekyllweb_updater.sh
  copy:
    dest={{jekyllweb_updater_ssh_wrapper}}
    src=external/jekyllweb_updater/github_ssh_wrapper.sh
    owner=root group=root mode=755

- name: Create the CGI root directory
  file:
    dest={{neicweb_cgi_dir}} state=directory
    owner=root group=root mode=755

- name: Install CGI scripts
  template:
    dest={{neicweb_cgi_dir}}/github-jekyll-update.{{item.cgi_key}}.cgi
    src=github-jekyll-update.cgi.j2
    owner=root group=root mode=755
  with_items: neicweb_sites.values()

### User

- name: Create privilege escalation user for the jekyllweb updater
  user: system=yes name={{jekyllweb_updater_user}}
        comment="jekyllweb_updater daemon"

### Directories

- file: dest={{jekyllweb_updater_log_dir}} state=directory mode=750
        owner={{jekyllweb_updater_user}} group={{jekyllweb_updater_user}}
- file: dest={{jekyllweb_updater_status_dir}} state=directory mode=755
        owner={{jekyllweb_updater_user}} group={{jekyllweb_updater_user}}

- file: dest={{jekyllweb_updater_cache_dir}}/{{item[0]}}/{{item[1]}}
        state=directory
        owner={{jekyllweb_updater_user}} group={{jekyllweb_updater_user}} mode=750
  with_nested:
    - neicweb_sites.keys()
    - [build, plugins, utils]

- file: dest={{item.webroot}}/html state=directory
        owner={{jekyllweb_updater_user}} group=apache mode=750
  with_items: neicweb_sites.values()

- git: dest={{jekyllweb_updater_trusted_cache_dir}}
       repo={{jekyllweb_updater_trusted_repo}}
  when: jekyllweb_updater_trusted_repo is defined

### Configuration and Service

- name: Install /etc/jekyllweb_updater.conf
  template: dest=/etc/jekyllweb_updater.conf src=jekyllweb_updater.conf.j2
            owner=root group=root mode=644

- name: Install updater service files
  template: dest=/usr/lib/systemd/system/jekyllweb_updater_{{item}}.service
            src=jekyllweb_updater.service.j2
            owner=root group=root mode=644
  vars:
    - site: "{{neicweb_sites[item]}}"
  with_items: neicweb_sites.keys()
  notify: [reload systemd]

- name: Enable updater services
  service: name=jekyllweb_updater_{{item}} state=running enabled=yes
  with_items: neicweb_sites.keys()
