### Software

- name: Install system packages
  yum: name={{item}} state=present
  with_items:
    - httpd
    - mod_ssl
    - mod_wsgi
    - nodejs
    - PyYAML


### Configure httpd

- name: Remove default httpd content
  file: dest=/etc/httpd/conf.d/{{item}} state=absent
  with_items: [welcome.conf, userdir.conf]

- name: Create /etc/httpd/conf.d/vhost-neic.nordforsk.org.d/
  file:
    dest=/etc/httpd/conf.d/vhost-neic.nordforsk.org.d/ state=directory
    owner=root group=root mode=755

- name: Create httpd log directories
  file:
    dest=/var/log/httpd/{{item.vhost}} state=directory
    owner=root group=root mode=644
  with_items: neicweb_sites.values()

- name: Install httpd configuration
  template:
    dest=/etc/httpd/conf.d/vhost-{{item}}.conf
    src=vhost-{{item}}.conf.j2
    owner=root group=root mode=644
  notify: [reload httpd]
  with_items:
  - neic.nordforsk.org


### Services and Firewall

- name: Enable httpd and firewalld services
  service: name={{item}} enabled=yes state=started
  with_items: [httpd, firewalld]

- name: Add dnat-http services to firewalld
  copy:
    dest=/etc/firewalld/services/dnat-https.xml src=dnat-https.xml
    owner=root group=root mode=644
  notify: [restart firewalld]
- meta: flush_handlers

- name: Open web services in firewalld
  firewalld: service={{item}} state=enabled permanent=true
  notify: [reload firewalld]
  with_items: [http, https, dnat-https]
