### System

- selinux: state=disabled # TODO
- lineinfile: dest=/etc/yum/yum-cron.conf
              regexp='^\s*apply_updates\s*=\s*' line='apply_updates = yes'


### Software

- yum: name={{item}} state=present
  with_items:
    - httpd
    - mod_ssl
    - mod_wsgi
    - nodejs
    - PyYAML
    - yum-cron


### Configure httpd

- file: dest=/etc/httpd/conf.d/welcome.conf state=absent
- file: dest=/etc/httpd/conf.d/userdir.conf state=absent

- file: dest=/var/log/httpd/{{item.vhost}} state=directory
        owner=root group=root mode=644
  with_items: neicweb_sites.values()

- template: dest=/etc/httpd/conf.d/vhost-{{item}}.conf
            src=vhost-{{item}}.conf.j2
            owner=root group=root mode=644
  notify: [reload httpd]
  with_items:
  - neic.nordforsk.org


### Services and Firewall

- service: name=httpd enabled=yes state=started
- service: name=firewalld enabled=yes state=started

- copy: dest=/etc/firewalld/services/dnat-https.xml src=dnat-https.xml
        owner=root group=root mode=644
  notify: [restart firewalld]
- meta: flush_handlers

- firewalld: service={{item}} state=enabled permanent=true
  notify: [reload firewalld]
  with_items: [http, https, dnat-https]


### Automatic Updates

- cron: name=pip_update cron_file=neicweb-ansible minute=37 hour=3 user=root
        job="{{pip_virtualenv}}/bin/pip freeze --local | grep -v '^\-e' | cut -d = -f 1  |
             xargs -n1 pip install -U"

- lineinfile: dest=/etc/aliases regexp='^root:' line='root{{':'}} {{mail_forward_root}}'
  notify: [newaliases]
  when: mail_forward_root is defined
