# System
# ======

- selinux: state=disabled # TODO
- lineinfile: dest=/etc/yum/yum-cron.conf
              regexp='^\s*apply_updates\s*=\s*' line='apply_updates = yes'


# Software
# ========

- yum: name={{item}} state=present
  with_items:
    - httpd
    - mod_ssl
    - mod_wsgi
    - nodejs
    - PyYAML
    - yum-cron


# Configure httpd
# ===============

- file: dest=/etc/httpd/conf.d/welcome.conf state=absent
- file: dest=/etc/httpd/conf.d/userdir.conf state=absent

- file: dest=/var/log/httpd/{{item}} state=directory
        owner=root group=root mode=644
  with_items:
  - neic.nordforsk.org
  - upload.neic.nordforsk.org

- template: dest=/etc/httpd/conf.d/vhost-{{item}}.conf
            src=vhost-{{item}}.conf.j2
            owner=root group=root mode=644
  notify: [reload httpd]
  with_items:
  - neic.nordforsk.org


# Services and Firewall
# =====================

- service: name=httpd enabled=yes state=started
- service: name=firewalld enabled=yes state=started

- copy: dest=/etc/firewalld/services/dnat-https.xml src=dnat-https.xml
        owner=root group=root mode=644

- firewalld: service={{item}} state=enabled permanent=true
  notify: [reload firewalld]
  with_items: [http, https, dnat-https]
